version: "3.9"

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"
    command: >
      bash -c '
         if [ ! -f config/certs/ca/ca.crt ]; then
           echo "Creating Certificate Authority";
           bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
           unzip config/certs/ca.zip -d config/certs;
         fi;
         if [ ! -f config/certs/certs/es01/es01.crt ]; then
           echo "Creating certs";
           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
           unzip config/certs/certs.zip -d config/certs;
         fi;
         echo "Setting file permissions"
         chown -R root:root config/certs;
         find . -type d -exec chmod 750 \{\} \;;
         find . -type f -exec chmod 640 \{\} \;;
         echo "All done!";
         '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - certgen:/usr/share/elasticsearch/config/certs
    configs:
      - target: /usr/share/elasticsearch/config/certs/instances.yml
        source: instances.yml

volumes:
  certgen:

configs:
  instances.yml:
    file: ./instances.yml
    name: instances.yml
    labels:
      name: elasticsearch
