{
 "title": "Kafka Topics Metrics",
 "description": "With Kafka Topics Metrics Dashboard we can visualize the Metrics related to the topic. We can select the particular topic from the dropdown and see the data related to this topic.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "ENV",
    "query": "label_values(system_uptime, env)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(kafka_controller_activecontrollers__1, instance)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(system_uptime, service)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_MessagesInPerSec_Count, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Message in by Topic",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_topic_MessagesInPerSec_Count{instance=~\"$host\",topic=\"$topic\",env=\"$env\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesInPerSec_OneMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesInPerSec_FiveMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesInPerSec_FifteenMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesOutPerSec_OneMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesOutPerSec_FiveMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_BytesOutPerSec_FifteenMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes in Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_MessagesInPerSec_OneMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequest Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_TotalProduceRequestsPerSec_OneMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "TotalFetchRequest Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_TotalFetchRequestsPerSec_OneMinuteRate{instance=~\"$host\",env=\"$env\",topic=\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}