version: "3.9"

services:
  postgres-01:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: postgres-01
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-01
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
      POSTGRESQL_POSTGRES_PASSWORD: ${HAPI_POSTGRES_PASSWORD}
    volumes:
      - "hapi-postgres-01-data:/bitnami/postgresql"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT}
          memory: ${HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE}
          memory: ${HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      pg_backup_net: {}

volumes:
  hapi-postgres-01-data:


networks:
  default:
    name: instant_default
  pg_backup_net:
    name: pg_backup
    driver: overlay
    attachable: true
