version: '3.9'

services:
  postgres-1:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${HF_POSTGRES_USERNAME:-admin}
      POSTGRES_PASSWORD: ${HF_POSTGRES_PASSWORD:-instant101}
      POSTGRES_DB: ${HF_POSTGRES_DB:-hapi}
    volumes:
      - 'hapi-postgres-1-data:/var/lib/postgresql/data'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}

  

volumes:
  hapi-postgres-1-data:
