{
 "title": "Container logs",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values({swarm_service_name=~\".+\"}, swarm_service_name)"
   },
   {
    "name": "task_name",
    "label": "Task",
    "query": "label_values({swarm_service_name=\"$service_name\"}, swarm_task_name)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({swarm_service_name=\"$service_name\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Total count of logs",
   "type": "stat",
   "description": "Total count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs (filtered by \"$searchable_pattern\")",
   "type": "logs",
   "description": "Live logs is a like 'tail -f | grep' in a real time",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (swarm_task_name)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (swarm_task_name)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"} |~ \"(?i)$searchable_pattern\")[30s])) by (swarm_task_name)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service_name=\"$service_name\", stream=~\"$stream\", swarm_task_name=~\"$task_name\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}