version: '3.9'

services:
  analytics-datastore-clickhouse-01:
    image: clickhouse/clickhouse-server
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-01:/var/lib/clickhouse/
    hostname: analytics-datastore-clickhouse-01
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-1"
    configs:
      - target: /etc/clickhouse-server/config.d/docker_related_config.xml
        source: docker_related_config.xml
      - target: /etc/clickhouse-server/config.d/enable_keeper.xml
        source: clickhouse_enable_keeper_01.xml
      - target: /etc/clickhouse-server/config.d/macros.xml
        source: clickhouse_macros_01.xml
      - target: /etc/clickhouse-server/config.d/remote_servers.xml
        source: clickhouse_remote_servers.xml
      - target: /etc/clickhouse-server/config.d/use_keeper.xml
        source: clickhouse_use_keeper.xml
    networks:
      public:
      dbt:
      default:

  analytics-datastore-clickhouse-02:
    image: clickhouse/clickhouse-server
    hostname: analytics-datastore-clickhouse-02
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-2"
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-02:/var/lib/clickhouse/
    configs:
      - target: /etc/clickhouse-server/config.d/docker_related_config.xml
        source: docker_related_config.xml
      - target: /etc/clickhouse-server/config.d/enable_keeper.xml
        source: clickhouse_enable_keeper_02.xml
      - target: /etc/clickhouse-server/config.d/macros.xml
        source: clickhouse_macros_02.xml
      - target: /etc/clickhouse-server/config.d/remote_servers.xml
        source: clickhouse_remote_servers.xml
      - target: /etc/clickhouse-server/config.d/use_keeper.xml
        source: clickhouse_use_keeper.xml
    networks:
      public:
      default:

  analytics-datastore-clickhouse-03:
    image: clickhouse/clickhouse-server
    hostname: analytics-datastore-clickhouse-03
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-3"
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-03:/var/lib/clickhouse/        
    configs:
      - target: /etc/clickhouse-server/config.d/docker_related_config.xml
        source: docker_related_config.xml
      - target: /etc/clickhouse-server/config.d/enable_keeper.xml
        source: clickhouse_enable_keeper_03.xml
      - target: /etc/clickhouse-server/config.d/macros.xml
        source: clickhouse_macros_03.xml
      - target: /etc/clickhouse-server/config.d/remote_servers.xml
        source: clickhouse_remote_servers.xml
      - target: /etc/clickhouse-server/config.d/use_keeper.xml
        source: clickhouse_use_keeper.xml
    networks:
      public:
      default:

  analytics-datastore-clickhouse-04:
    image: clickhouse/clickhouse-server
    hostname: analytics-datastore-clickhouse-04
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-04:/var/lib/clickhouse/        
    configs:
      - target: /etc/clickhouse-server/config.d/docker_related_config.xml
        source: docker_related_config.xml
      - target: /etc/clickhouse-server/config.d/macros.xml
        source: clickhouse_macros_04.xml
      - target: /etc/clickhouse-server/config.d/remote_servers.xml
        source: clickhouse_remote_servers.xml
      - target: /etc/clickhouse-server/config.d/use_keeper.xml
        source: clickhouse_use_keeper.xml
    networks:
      public:
      default:

volumes:
  clickhouse-data-01:
  clickhouse-data-02:
  clickhouse-data-03:
  clickhouse-data-04:
  
configs:
  docker_related_config.xml:
    file: ./cluster_configs/docker_related_config.xml
    name: docker_related_config.xml-${docker_related_config_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_enable_keeper_01.xml:
    file: ./cluster_configs/enable_keeper_01.xml
    name: enable_keeper_01.xml-${enable_keeper_01_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_enable_keeper_02.xml:
    file: ./cluster_configs/enable_keeper_02.xml
    name: enable_keeper_02.xml-${enable_keeper_02_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_enable_keeper_03.xml:
    file: ./cluster_configs/enable_keeper_03.xml
    name: enable_keeper_03.xml-${enable_keeper_03_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_macros_01.xml:
    file: ./cluster_configs/macros_01.xml
    name: macros_01.xml-${macros_01_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_macros_02.xml:
    file: ./cluster_configs/macros_02.xml
    name: macros_02.xml-${macros_02_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_macros_03.xml:
    file: ./cluster_configs/macros_03.xml
    name: macros_03.xml-${macros_03_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_macros_04.xml:
    file: ./cluster_configs/macros_04.xml
    name: macros_04.xml-${macros_04_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_remote_servers.xml:
    file: ./cluster_configs/remote_servers.xml
    name: remote_servers.xml-${remote_servers_xml_DIGEST:?err}
    labels: 
      name: clickhouse
  clickhouse_use_keeper.xml:
    file: ./cluster_configs/use_keeper.xml
    name: use_keeper.xml-${use_keeper_xml_DIGEST:?err}
    labels: 
      name: clickhouse

networks:
  public:
    name: clickhouse_public
    external: true
  default:
