version: '3.9'

services:
  kafka:
    hostname: kafka-{{.Node.Hostname}}
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: ${KAFKA_INSTANCES}
      resources:
        limits:
          cpus: ${KAFKA_CPU_LIMIT}
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          cpus: ${KAFKA_CPU_RESERVE}
          memory: ${KAFKA_MEMORY_RESERVE}

volumes:
  kafka-volume:
