version: '3.9'

services:
  kafka-01:
    environment:
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9093,2@kafka-02:9093,3@kafka-03:9093
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  kafka-02:
    image: bitnami/kafka:3.4.0
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    environment:
      BITNAMI_DEBUG: ${KAFKA_DEBUG}
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: 'ehB92ChxEe2iYQAAAkKsEg'
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-02:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9093,2@kafka-02:9093,3@kafka-03:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    volumes:
      - kafka-02-data:/bitnami/kafka
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          memory: ${KAFKA_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    networks:
      public:
      default:

  kafka-03:
    image: bitnami/kafka:3.4.0
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    environment:
      BITNAMI_DEBUG: ${KAFKA_DEBUG}
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: 'ehB92ChxEe2iYQAAAkKsEg'
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-03:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9093,2@kafka-02:9093,3@kafka-03:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    volumes:
      - kafka-03-data:/bitnami/kafka    
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          memory: ${KAFKA_MEMORY_RESERVE}
      restart_policy:
        condition: on-failure
    networks:
      public:
      default:

volumes:
  kafka-02-data:
  kafka-03-data:
