version: '3.9'

services:
  kafka-unbundler-consumer:
    image: jembi/kafka-unbundler-consumer:0.0.3
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
    networks:
      kafka:

networks:
  kafka:
    name: kafka_public
    external: true
