version: "3.9"

services:
  minio-01:
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MINIO_01_PLACEMENT}"

  minio-02:
    image: ${MINIO_IMAGE}
    entrypoint: sh
    command: -c 'mkdir -p /data1/loki /data2/loki && minio server --console-address ":9001" --address ":9090" http://minio-0{1...4}/data{1...2}'
    environment:
      MINIO_ROOT_USER: ${MO_SECURITY_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MO_SECURITY_ADMIN_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio-02
    volumes:
      - minio-02-data1:/data1
      - minio-02-data2:/data2
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MINIO_02_PLACEMENT}"
      replicas: 1

  minio-03:
    image: ${MINIO_IMAGE}
    entrypoint: sh
    command: -c 'mkdir -p /data1/loki /data2/loki && minio server --console-address ":9001" --address ":9090" http://minio-0{1...4}/data{1...2}'
    environment:
      MINIO_ROOT_USER: ${MO_SECURITY_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MO_SECURITY_ADMIN_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio-03
    volumes:
      - minio-03-data1:/data1
      - minio-03-data2:/data2
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MINIO_03_PLACEMENT}"
      replicas: 1

  minio-04:
    image: ${MINIO_IMAGE}
    entrypoint: sh
    command: -c 'mkdir -p /data1/loki /data2/loki && minio server --console-address ":9001" --address ":9090" http://minio-0{1...4}/data{1...2}'
    environment:
      MINIO_ROOT_USER: ${MO_SECURITY_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MO_SECURITY_ADMIN_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio-04
    volumes:
      - minio-04-data1:/data1
      - minio-04-data2:/data2
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MINIO_04_PLACEMENT}"
      replicas: 1

volumes:
  minio-02-data1:
  minio-02-data2:
  minio-03-data1:
  minio-03-data2:
  minio-04-data1:
  minio-04-data2:
