name: Platform's docker images vulnerability scan

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scan-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Run trivy vulnerability scanner for the OpenHIM core image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/openhim-core:7
          format: 'sarif'
          output: 'trivy-results.sarif'
        
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run trivy vulnerability scanner for the OpenHIM console image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/openhim-console:1.14.4
          format: 'sarif'
          output: 'trivy-results.sarif'
        
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
